name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true

      # ESLint needs to be able to resolve 'manten' to allow shadowing
      - name: Build
        run: pnpm build

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Test (Node)
        run: pnpm concurrently "pnpm test" "NODE_OPTIONS='--import=tsx/esm' pnpm run --use-node-version=20.20.0 test"

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: Test (Bun)
        run: pnpm test:bun
